alter table address_book drop foreign key FKFB8B05475CB2D09;
alter table app_control drop foreign key FKEE00D53FC4027D76;
alter table app_control drop foreign key FKEE00D53F1D457434;
alter table app_control drop foreign key FKEE00D53F1CD5CA34;
alter table base_entity drop foreign key FK7A02BD11C4027D76;
alter table branch drop foreign key FKADAF25A2EDBCEC59;
alter table branch drop foreign key FKADAF25A2A0FA3AD6;
alter table cal_event drop foreign key FKABCCC2E9C9A2A33E;
alter table calendar drop foreign key FKF55EFB3E75CB2D09;
alter table comment drop foreign key FK38A5EE5F889319BC;
alter table commit_item drop foreign key FK5A19351B2AEC5E14;
alter table contact drop foreign key FK38B7242012BCE54F;
alter table contact_extended_properties drop foreign key FK91B6895A8A92AD65;
alter table contact_extended_properties drop foreign key FK91B6895AFCBFFB3E;
alter table contact_extended_property drop foreign key FK8C45B7BCFCBFFB3E;
alter table credential drop foreign key FKD743E857666EC650;
alter table email_item drop foreign key FK4E94C9D642E056DC;
alter table email_item drop foreign key FK4E94C9D6A9C1AEC0;
alter table email_item drop foreign key FK4E94C9D6E4A566FC;
alter table email_send_attempt drop foreign key FK7EF81CD9C331BB44;
alter table fanout_entry drop foreign key FKD6C6228E4FF762A6;
alter table forum drop foreign key FK5D18D211D457434;
alter table forum_post drop foreign key FKCDDDD0FE889319BC;
alter table forum_post drop foreign key FKCDDDD0FEA576D8FE;
alter table forum_reply drop foreign key FKEDF3E64C889319BC;
alter table forum_reply drop foreign key FKEDF3E64C70AD9EA0;
alter table forum_topic drop foreign key FKEE14A0918F132661;
alter table group_email_job drop foreign key FKF4C306DAC4027D76;
alter table group_entity drop foreign key FKDC016DA36F774771;
alter table group_membership drop foreign key FK52631962F39C4F0;
alter table group_membership drop foreign key FK5263196D360BEA0;
alter table group_recipient drop foreign key FKA73C90592840C316;
alter table group_recipient drop foreign key FKA73C9059E4A566FC;
alter table nv_pair drop foreign key FK89B86AF1E979F767;
alter table nv_pair drop foreign key FK89B86AF1A0FA3AD6;
alter table org_entity drop foreign key FK11F8699E6F774771;
alter table permission drop foreign key FKE125C5CF1551AA62;
alter table permission drop foreign key FKE125C5CF802C3112;
alter table permission drop foreign key FKE125C5CF9DBB8815;
alter table post drop foreign key FK3498A01D457434;
alter table post drop foreign key FK3498A03E5139F4;
alter table profile drop foreign key FKED8E89A96F774771;
alter table profile drop foreign key FKED8E89A98B021E90;
alter table repository drop foreign key FK7446DB4AE979F767;
alter table website drop foreign key FK48F9E09BC4027D76;
alter table website drop foreign key FK48F9E09BA0FA3AD6;
drop table if exists address_book;
drop table if exists alt_format;
drop table if exists app_control;
drop table if exists base_entity;
drop table if exists blob_hash;
drop table if exists branch;
drop table if exists cal_event;
drop table if exists calendar;
drop table if exists comment;
drop table if exists commit_item;
drop table if exists contact;
drop table if exists contact_extended_properties;
drop table if exists contact_extended_property;
drop table if exists credential;
drop table if exists data_item;
drop table if exists email_item;
drop table if exists email_send_attempt;
drop table if exists fanout_entry;
drop table if exists fanout_hash;
drop table if exists forum;
drop table if exists forum_post;
drop table if exists forum_reply;
drop table if exists forum_topic;
drop table if exists group_email_job;
drop table if exists group_entity;
drop table if exists group_membership;
drop table if exists group_recipient;
drop table if exists item_history;
drop table if exists named_counter;
drop table if exists nv_pair;
drop table if exists org_entity;
drop table if exists permission;
drop table if exists post;
drop table if exists profile;
drop table if exists repository;
drop table if exists version;
drop table if exists website;
create table address_book (id bigint not null auto_increment, description varchar(255), created_date datetime not null, modified_date datetime not null, name varchar(255) not null, owner bigint, primary key (id));
create table alt_format (id bigint not null auto_increment, source_hash bigint not null, alt_hash bigint not null, name varchar(255) not null, primary key (id), unique (name, source_hash));
create table app_control (id bigint not null auto_increment, modified_date datetime not null, enabled bit not null, name varchar(255) not null, organisation bigint, modified_by bigint not null, website bigint, primary key (id));
create table base_entity (id bigint not null auto_increment, created_date datetime not null, modified_date datetime not null, notes varchar(255), name varchar(255) not null, type varchar(255), organisation bigint, primary key (id), unique (name, organisation));
create table blob_hash (blob_hash bigint not null, volume_id bigint not null, primary key (blob_hash));
create table branch (id bigint not null auto_increment, created_date datetime, lockversion bigint, name varchar(255), head bigint not null, repository bigint not null, primary key (id));
create table cal_event (id bigint not null auto_increment, description varchar(255), created_date datetime not null, modified_date datetime not null, ctag bigint not null, start_date datetime not null, end_date datetime not null, timezone varchar(255), summary varchar(255), name varchar(255) not null, calendar bigint not null, primary key (id));
create table calendar (id bigint not null auto_increment, created_date datetime not null, modified_date datetime not null, color varchar(255), ctag bigint not null, name varchar(255) not null, owner bigint not null, primary key (id), unique (name, owner));
create table comment (id bigint not null, content_id tinyblob not null, content_href varchar(255) not null, content_title varchar(255) not null, primary key (id));
create table commit_item (id bigint not null auto_increment, created_date datetime, item_hash bigint, editor bigint not null, primary key (id));
create table contact (id bigint not null auto_increment, created_date datetime not null, modified_date datetime not null, sur_name varchar(255), given_name varchar(255), mail varchar(255), organization_name varchar(255), telephonenumber varchar(255), uid varchar(255) not null, name varchar(255) not null, address_book bigint not null, primary key (id));
create table contact_extended_properties (contact bigint not null, extended_properties bigint not null, unique (extended_properties));
create table contact_extended_property (id bigint not null auto_increment, prop_value varchar(255) not null, name varchar(255) not null, contact bigint not null, primary key (id));
create table credential (type varchar(20) not null, id bigint not null auto_increment, created_date datetime not null, modified_date datetime not null, password varchar(255) not null, profile bigint not null, primary key (id));
create table data_item (id bigint not null auto_increment, item_hash bigint not null, parent_hash bigint not null, name text, type varchar(1) not null, primary key (id), unique (name, parent_hash));
create table email_item (id bigint not null auto_increment, created_date datetime not null, reply_to_address varchar(255) not null, subject varchar(255) not null, html varchar(255), send_status varchar(255), send_status_date datetime not null, read_status bit not null, message_size integer not null, disposition varchar(255), bcc_list varchar(255), cc_list varchar(255), content_language varchar(255), to_list varchar(255), from_address varchar(255) not null, recipient_address varchar(255) not null, text varchar(255), encoding varchar(255), sender bigint, job bigint, recipient bigint, primary key (id));
create table email_send_attempt (id bigint not null auto_increment, status_date datetime not null, status varchar(255), email_item bigint not null, primary key (id));
create table fanout_entry (id bigint not null auto_increment, chunk_hash bigint, fanout bigint, primary key (id));
create table fanout_hash (fanout_hash bigint not null, actual_content_length bigint not null, primary key (fanout_hash));
create table forum (id bigint not null auto_increment, notes varchar(255), title varchar(255) not null, name varchar(255) not null, website bigint not null, primary key (id));
create table forum_post (id bigint not null, title varchar(255) not null, name varchar(255) not null, topic bigint not null, primary key (id));
create table forum_reply (id bigint not null, post bigint not null, primary key (id));
create table forum_topic (id bigint not null auto_increment, notes varchar(255), title varchar(255) not null, name varchar(255) not null, forum bigint not null, primary key (id));
create table group_email_job (id bigint not null auto_increment, notes varchar(255), title varchar(255) not null, subject varchar(255) not null, from_address varchar(255) not null, status_date datetime not null, status varchar(255), name varchar(255) not null, organisation bigint not null, primary key (id));
create table group_entity (id bigint not null, primary key (id));
create table group_membership (id bigint not null auto_increment, created_date datetime not null, modified_date datetime not null, group_entity bigint not null, member bigint not null, primary key (id));
create table group_recipient (id bigint not null auto_increment, job bigint not null, recipient bigint not null, primary key (id));
create table item_history (id bigint not null auto_increment, tree_item tinyblob not null, parent_tree_item tinyblob not null, action varchar(255) not null, name text, primary key (id));
create table named_counter (id bigint not null auto_increment, counter bigint not null, name varchar(255), primary key (id));
create table nv_pair (id bigint not null auto_increment, prop_value varchar(255) not null, name varchar(255) not null, repository bigint, base_entity bigint, primary key (id));
create table org_entity (id bigint not null, primary key (id));
create table permission (id bigint not null auto_increment, grantee_principal varchar(255), priviledge integer, granted_on_entity bigint, grantee bigint, granted_on_branch bigint, primary key (id));
create table post (id bigint not null auto_increment, notes varchar(255), post_date datetime not null, website bigint not null, poster bigint not null, primary key (id));
create table profile (id bigint not null, email varchar(255), sur_name varchar(255), first_name varchar(255), nick_name varchar(255), photo_href varchar(255), phone varchar(255), admin_org bigint not null, primary key (id));
create table repository (id bigint not null auto_increment, created_date datetime not null, notes varchar(255), title varchar(255), name varchar(255) not null, base_entity bigint not null, primary key (id), unique (name, base_entity));
create table version (id bigint not null auto_increment, resource_hash bigint not null, previous_mod_hash bigint not null, profile_id bigint not null, mod_date datetime not null, mod_hash bigint not null, primary key (id));
create table website (id bigint not null auto_increment, created_date datetime not null, internal_theme varchar(255), public_theme varchar(255), current_branch varchar(255), name varchar(255) not null, repository bigint not null, organisation bigint not null, primary key (id));
alter table address_book add index FKFB8B05475CB2D09 (owner), add constraint FKFB8B05475CB2D09 foreign key (owner) references base_entity (id);
alter table app_control add index FKEE00D53FC4027D76 (organisation), add constraint FKEE00D53FC4027D76 foreign key (organisation) references org_entity (id);
alter table app_control add index FKEE00D53F1D457434 (website), add constraint FKEE00D53F1D457434 foreign key (website) references website (id);
alter table app_control add index FKEE00D53F1CD5CA34 (modified_by), add constraint FKEE00D53F1CD5CA34 foreign key (modified_by) references profile (id);
alter table base_entity add index FK7A02BD11C4027D76 (organisation), add constraint FK7A02BD11C4027D76 foreign key (organisation) references org_entity (id);
alter table branch add index FKADAF25A2EDBCEC59 (head), add constraint FKADAF25A2EDBCEC59 foreign key (head) references commit_item (id);
alter table branch add index FKADAF25A2A0FA3AD6 (repository), add constraint FKADAF25A2A0FA3AD6 foreign key (repository) references repository (id);
alter table cal_event add index FKABCCC2E9C9A2A33E (calendar), add constraint FKABCCC2E9C9A2A33E foreign key (calendar) references calendar (id);
alter table calendar add index FKF55EFB3E75CB2D09 (owner), add constraint FKF55EFB3E75CB2D09 foreign key (owner) references base_entity (id);
alter table comment add index FK38A5EE5F889319BC (id), add constraint FK38A5EE5F889319BC foreign key (id) references post (id);
alter table commit_item add index FK5A19351B2AEC5E14 (editor), add constraint FK5A19351B2AEC5E14 foreign key (editor) references profile (id);
alter table contact add index FK38B7242012BCE54F (address_book), add constraint FK38B7242012BCE54F foreign key (address_book) references address_book (id);
alter table contact_extended_properties add index FK91B6895A8A92AD65 (extended_properties), add constraint FK91B6895A8A92AD65 foreign key (extended_properties) references contact_extended_property (id);
alter table contact_extended_properties add index FK91B6895AFCBFFB3E (contact), add constraint FK91B6895AFCBFFB3E foreign key (contact) references contact (id);
alter table contact_extended_property add index FK8C45B7BCFCBFFB3E (contact), add constraint FK8C45B7BCFCBFFB3E foreign key (contact) references contact (id);
alter table credential add index FKD743E857666EC650 (profile), add constraint FKD743E857666EC650 foreign key (profile) references profile (id);
alter table email_item add index FK4E94C9D642E056DC (sender), add constraint FK4E94C9D642E056DC foreign key (sender) references profile (id);
alter table email_item add index FK4E94C9D6A9C1AEC0 (recipient), add constraint FK4E94C9D6A9C1AEC0 foreign key (recipient) references profile (id);
alter table email_item add index FK4E94C9D6E4A566FC (job), add constraint FK4E94C9D6E4A566FC foreign key (job) references group_email_job (id);
alter table email_send_attempt add index FK7EF81CD9C331BB44 (email_item), add constraint FK7EF81CD9C331BB44 foreign key (email_item) references email_item (id);
alter table fanout_entry add index FKD6C6228E4FF762A6 (fanout), add constraint FKD6C6228E4FF762A6 foreign key (fanout) references fanout_hash (fanout_hash);
alter table forum add index FK5D18D211D457434 (website), add constraint FK5D18D211D457434 foreign key (website) references website (id);
alter table forum_post add index FKCDDDD0FE889319BC (id), add constraint FKCDDDD0FE889319BC foreign key (id) references post (id);
alter table forum_post add index FKCDDDD0FEA576D8FE (topic), add constraint FKCDDDD0FEA576D8FE foreign key (topic) references forum_topic (id);
alter table forum_reply add index FKEDF3E64C889319BC (id), add constraint FKEDF3E64C889319BC foreign key (id) references post (id);
alter table forum_reply add index FKEDF3E64C70AD9EA0 (post), add constraint FKEDF3E64C70AD9EA0 foreign key (post) references forum_post (id);
alter table forum_topic add index FKEE14A0918F132661 (forum), add constraint FKEE14A0918F132661 foreign key (forum) references forum (id);
alter table group_email_job add index FKF4C306DAC4027D76 (organisation), add constraint FKF4C306DAC4027D76 foreign key (organisation) references org_entity (id);
alter table group_entity add index FKDC016DA36F774771 (id), add constraint FKDC016DA36F774771 foreign key (id) references base_entity (id);
alter table group_membership add index FK52631962F39C4F0 (member), add constraint FK52631962F39C4F0 foreign key (member) references base_entity (id);
alter table group_membership add index FK5263196D360BEA0 (group_entity), add constraint FK5263196D360BEA0 foreign key (group_entity) references group_entity (id);
alter table group_recipient add index FKA73C90592840C316 (recipient), add constraint FKA73C90592840C316 foreign key (recipient) references group_entity (id);
alter table group_recipient add index FKA73C9059E4A566FC (job), add constraint FKA73C9059E4A566FC foreign key (job) references group_email_job (id);
alter table nv_pair add index FK89B86AF1E979F767 (base_entity), add constraint FK89B86AF1E979F767 foreign key (base_entity) references base_entity (id);
alter table nv_pair add index FK89B86AF1A0FA3AD6 (repository), add constraint FK89B86AF1A0FA3AD6 foreign key (repository) references repository (id);
alter table org_entity add index FK11F8699E6F774771 (id), add constraint FK11F8699E6F774771 foreign key (id) references base_entity (id);
alter table permission add index FKE125C5CF1551AA62 (granted_on_branch), add constraint FKE125C5CF1551AA62 foreign key (granted_on_branch) references branch (id);
alter table permission add index FKE125C5CF802C3112 (grantee), add constraint FKE125C5CF802C3112 foreign key (grantee) references base_entity (id);
alter table permission add index FKE125C5CF9DBB8815 (granted_on_entity), add constraint FKE125C5CF9DBB8815 foreign key (granted_on_entity) references base_entity (id);
alter table post add index FK3498A01D457434 (website), add constraint FK3498A01D457434 foreign key (website) references website (id);
alter table post add index FK3498A03E5139F4 (poster), add constraint FK3498A03E5139F4 foreign key (poster) references profile (id);
alter table profile add index FKED8E89A96F774771 (id), add constraint FKED8E89A96F774771 foreign key (id) references base_entity (id);
alter table profile add index FKED8E89A98B021E90 (admin_org), add constraint FKED8E89A98B021E90 foreign key (admin_org) references org_entity (id);
alter table repository add index FK7446DB4AE979F767 (base_entity), add constraint FK7446DB4AE979F767 foreign key (base_entity) references base_entity (id);
alter table website add index FK48F9E09BC4027D76 (organisation), add constraint FK48F9E09BC4027D76 foreign key (organisation) references org_entity (id);
alter table website add index FK48F9E09BA0FA3AD6 (repository), add constraint FK48F9E09BA0FA3AD6 foreign key (repository) references repository (id);
