drop table access_log cascade constraints;
drop table address_book cascade constraints;
drop table alt_format cascade constraints;
drop table app_control cascade constraints;
drop table app_setting cascade constraints;
drop table base_email_job cascade constraints;
drop table base_entity cascade constraints;
drop table base_process cascade constraints;
drop table blob_hash cascade constraints;
drop table branch cascade constraints;
drop table cal_event cascade constraints;
drop table cal_event_process cascade constraints;
drop table calendar cascade constraints;
drop table certificate cascade constraints;
drop table comment cascade constraints;
drop table commit_item cascade constraints;
drop table contact cascade constraints;
drop table contact_extended_property cascade constraints;
drop table credential cascade constraints;
drop table email_item cascade constraints;
drop table email_send_attempt cascade constraints;
drop table email_trigger cascade constraints;
drop table enrolement cascade constraints;
drop table fanout_entry cascade constraints;
drop table fanout_hash cascade constraints;
drop table forum cascade constraints;
drop table forum_post cascade constraints;
drop table forum_reply cascade constraints;
drop table group_email_job cascade constraints;
drop table group_entity cascade constraints;
drop table group_in_website cascade constraints;
drop table group_membership cascade constraints;
drop table group_membership_application cascade constraints;
drop table group_recipient cascade constraints;
drop table group_reward cascade constraints;
drop table group_role cascade constraints;
drop table learner_process cascade constraints;
drop table learning_log cascade constraints;
drop table media_meta_data cascade constraints;
drop table membership_process cascade constraints;
drop table module_status cascade constraints;
drop table module_status_field cascade constraints;
drop table module_status_process cascade constraints;
drop table named_counter cascade constraints;
drop table nv_pair cascade constraints;
drop table org_entity cascade constraints;
drop table password_reset cascade constraints;
drop table post cascade constraints;
drop table profile cascade constraints;
drop table quiz_answer cascade constraints;
drop table quiz_attempt cascade constraints;
drop table repository cascade constraints;
drop table reward cascade constraints;
drop table reward_entry cascade constraints;
drop table signup_log cascade constraints;
drop table sub_org cascade constraints;
drop table subordinate cascade constraints;
drop table version cascade constraints;
drop table website cascade constraints;
drop sequence hibernate_sequence;
create table access_log (id number(19,0) not null, content_type varchar2(255 char), duration_ms number(19,0), num_bytes number(19,0), referrer varchar2(1024 char), req_date timestamp not null, req_day number(10,0) not null, req_from varchar2(255 char), req_host varchar2(255 char), req_hour number(10,0) not null, req_method varchar2(255 char) not null, req_month number(10,0) not null, req_user varchar2(255 char), req_year number(10,0) not null, result_code number(10,0) not null, url varchar2(255 char), organisation number(19,0), website number(19,0), primary key (id));
create table address_book (id number(19,0) not null, primary key (id));
create table alt_format (id number(19,0) not null, alt_hash varchar2(255 char) not null, name varchar2(255 char) not null, source_hash varchar2(255 char) not null, primary key (id), unique (name, source_hash));
create table app_control (id number(19,0) not null, enabled number(1,0) not null, modified_date timestamp not null, name varchar2(255 char) not null, modified_by number(19,0) not null, organisation number(19,0), website_branch number(19,0), primary key (id), unique (name, organisation, website_branch));
create table app_setting (id number(19,0) not null, name varchar2(255 char) not null, prop_value varchar2(255 char), app_control number(19,0), primary key (id), unique (app_control, name));
create table base_email_job (id number(19,0) not null, from_address varchar2(255 char), html varchar2(255 char), name varchar2(255 char) not null, notes varchar2(255 char), subject varchar2(255 char), title varchar2(255 char), type varchar2(255 char), organisation number(19,0) not null, primary key (id));
create table base_entity (id number(19,0) not null, created_date timestamp not null, modified_date timestamp not null, name varchar2(255 char) not null, notes varchar2(255 char), type varchar2(255 char), primary key (id), unique (name));
create table base_process (id number(19,0) not null, process_name varchar2(255 char), process_version number(10,0) not null, state_name varchar2(255 char), time_entered timestamp, type varchar2(255 char), primary key (id));
create table blob_hash (blob_hash number(19,0) not null, volume_id number(19,0) not null, primary key (blob_hash));
create table branch (id number(19,0) not null, created_date timestamp, internal_theme varchar2(255 char), name varchar2(255 char), public_theme varchar2(255 char), lockversion number(19,0), from_commit number(19,0), head number(19,0) not null, repository number(19,0) not null, primary key (id), unique (repository, name));
create table cal_event (id number(19,0) not null, created_date timestamp not null, ctag number(19,0) not null, description varchar2(255 char), end_date timestamp not null, modified_date timestamp not null, name varchar2(255 char) not null, start_date timestamp not null, summary varchar2(255 char), timezone varchar2(255 char), calendar number(19,0) not null, primary key (id));
create table cal_event_process (id number(19,0) not null, cal_event number(19,0) not null, primary key (id));
create table calendar (id number(19,0) not null, color varchar2(255 char), created_date timestamp not null, ctag number(19,0) not null, modified_date timestamp not null, name varchar2(255 char) not null, owner number(19,0) not null, primary key (id), unique (name, owner));
create table certificate (id number(19,0) not null, background_image_hash varchar2(255 char), name varchar2(255 char) not null, text varchar2(255 char), title varchar2(255 char) not null, organisation number(19,0) not null, primary key (id), unique (name, organisation));
create table comment (content_href varchar2(255 char) not null, content_id varchar2(255 char) not null, content_title varchar2(255 char) not null, id number(19,0) not null, primary key (id));
create table commit_item (id number(19,0) not null, created_date timestamp, item_hash varchar2(255 char), previous_commit_id number(19,0), branch number(19,0), editor number(19,0) not null, primary key (id));
create table contact (id number(19,0) not null, given_name varchar2(255 char), mail varchar2(255 char), name varchar2(255 char) not null, organization_name varchar2(255 char), sur_name varchar2(255 char), telephonenumber varchar2(255 char), uid varchar2(255 char) not null, address_book number(19,0) not null, primary key (id));
create table contact_extended_property (id number(19,0) not null, name varchar2(255 char) not null, prop_value varchar2(255 char) not null, contact number(19,0) not null, primary key (id));
create table credential (type varchar2(20 char) not null, id number(19,0) not null, created_date timestamp not null, modified_date timestamp not null, password varchar2(255 char) not null, profile number(19,0) not null, primary key (id));
create table email_item (id number(19,0) not null, bcc_list varchar2(255 char), cc_list varchar2(255 char), content_language varchar2(255 char), created_date timestamp not null, disposition varchar2(255 char), encoding varchar2(255 char), from_address varchar2(255 char) not null, html long, message_size number(10,0) not null, next_attempt timestamp, num_attempts number(10,0), read_status number(1,0) not null, recipient_address varchar2(255 char) not null, reply_to_address varchar2(255 char) not null, send_status varchar2(255 char), send_status_date timestamp not null, subject varchar2(255 char) not null, text long, to_list varchar2(255 char), email_trigger number(19,0), job number(19,0), recipient number(19,0), sender number(19,0), primary key (id));
create table email_send_attempt (id number(19,0) not null, status varchar2(255 char), status_date timestamp not null, email_item number(19,0) not null, primary key (id));
create table email_trigger (enabled number(1,0) not null, event_id varchar2(255 char) not null, include_user number(1,0) not null, trigger_condition1 varchar2(255 char), trigger_condition2 varchar2(255 char), trigger_condition3 varchar2(255 char), trigger_condition4 varchar2(255 char), trigger_condition5 varchar2(255 char), id number(19,0) not null, primary key (id));
create table enrolement (id number(19,0) not null, completable number(1,0), created_date date not null, enroled_course varchar2(255 char), enroled_program varchar2(255 char) not null, modified_date date not null, enroled_group number(19,0) not null, website number(19,0) not null, primary key (id));
create table fanout_entry (id number(19,0) not null, chunk_hash varchar2(255 char), fanout number(19,0), primary key (id));
create table fanout_hash (id number(19,0) not null, actual_content_length number(19,0) not null, fanout_hash varchar2(255 char) not null, type varchar2(255 char) not null, primary key (id), unique (type, fanout_hash));
create table forum (id number(19,0) not null, name varchar2(255 char) not null, notes varchar2(255 char), title varchar2(255 char) not null, website number(19,0) not null, primary key (id));
create table forum_post (name varchar2(255 char) not null, title varchar2(255 char) not null, id number(19,0) not null, forum number(19,0) not null, primary key (id));
create table forum_reply (id number(19,0) not null, post number(19,0) not null, primary key (id));
create table group_email_job (status varchar2(255 char), status_date timestamp not null, id number(19,0) not null, primary key (id));
create table group_entity (id number(19,0) not null, created_date timestamp not null, modified_date timestamp not null, name varchar2(255 char) not null, registration_mode varchar2(255 char) not null, organisation number(19,0) not null, primary key (id));
create table group_in_website (id number(19,0) not null, user_group number(19,0) not null, website number(19,0) not null, primary key (id), unique (user_group, website));
create table group_membership (id number(19,0) not null, created_date timestamp not null, modified_date timestamp not null, group_entity number(19,0) not null, member number(19,0) not null, within_org number(19,0) not null, primary key (id), unique (member, group_entity, within_org));
create table group_membership_application (id number(19,0) not null, created_date timestamp not null, modified_date timestamp not null, admin_org number(19,0) not null, group_entity number(19,0) not null, member number(19,0) not null, website number(19,0), within_org number(19,0) not null, primary key (id));
create table group_recipient (id number(19,0) not null, job number(19,0) not null, recipient number(19,0) not null, primary key (id));
create table group_reward (id number(19,0) not null, created_date date, group_to_reward number(19,0) not null, reward number(19,0) not null, primary key (id), unique (group_to_reward, reward));
create table group_role (id number(19,0) not null, role_name varchar2(255 char) not null, grantee number(19,0) not null, repository number(19,0), within_org number(19,0), primary key (id), unique (role_name, grantee, within_org, repository));
create table learner_process (program_code varchar2(255 char), id number(19,0) not null, profile number(19,0) not null, primary key (id));
create table learning_log (id number(19,0) not null, action varchar2(255 char) not null, course_code varchar2(255 char) not null, program_code varchar2(255 char) not null, req_date timestamp not null, req_day number(10,0) not null, req_hour number(10,0) not null, req_month number(10,0) not null, req_year number(10,0) not null, organisation number(19,0) not null, profile number(19,0) not null, website number(19,0), primary key (id));
create table media_meta_data (id number(19,0) not null, duration_secs number(10,0), height number(10,0), recorded_date timestamp, source_hash varchar2(255 char) not null, width number(10,0), primary key (id), unique (source_hash));
create table membership_process (membership raw(255), id number(19,0) not null, primary key (id));
create table module_status (id number(19,0) not null, complete number(1,0), course_code varchar2(255 char) not null, created_date date not null, current_page varchar2(255 char), modified_date date not null, module_code varchar2(255 char) not null, percent_complete number(10,0), program_code varchar2(255 char) not null, profile number(19,0) not null, website number(19,0) not null, primary key (id), unique (website, program_code, course_code, module_code, profile));
create table module_status_field (id number(19,0) not null, mod_date date, name varchar2(255 char) not null, prop_value varchar2(255 char) not null, module_status number(19,0), primary key (id));
create table module_status_process (id number(19,0) not null, module_status number(19,0) not null, primary key (id));
create table named_counter (id number(19,0) not null, counter number(19,0) not null, name varchar2(255 char), primary key (id));
create table nv_pair (id number(19,0) not null, name varchar2(255 char) not null, prop_value varchar2(255 char) not null, base_entity number(19,0), primary key (id));
create table org_entity (deleted number(1,0), org_id varchar2(255 char) not null, title varchar2(255 char), id number(19,0) not null, organisation number(19,0), primary key (id), unique (org_id));
create table password_reset (id number(19,0) not null, created_date timestamp not null, return_url varchar2(255 char) not null, token varchar2(255 char), profile number(19,0) not null, website number(19,0), primary key (id), unique (token));
create table post (id number(19,0) not null, notes varchar2(2048 char), post_date timestamp not null, poster number(19,0) not null, website number(19,0) not null, primary key (id));
create table profile (email varchar2(255 char), enabled number(1,0) not null, first_name varchar2(255 char), nick_name varchar2(255 char), phone varchar2(255 char), photo_hash varchar2(255 char), rejected number(1,0) not null, sur_name varchar2(255 char), id number(19,0) not null, primary key (id));
create table quiz_answer (id number(19,0) not null, actual_answer varchar2(255 char), answer_key varchar2(255 char) not null, given_answer varchar2(255 char) not null, quiz_attempt number(19,0), primary key (id));
create table quiz_attempt (id number(19,0) not null, created_date date not null, passed number(1,0), module_status number(19,0) not null, primary key (id));
create table repository (id number(19,0) not null, created_date timestamp not null, deleted number(1,0), live_branch varchar2(255 char), name varchar2(255 char) not null, notes varchar2(255 char), public_content number(1,0) not null, title varchar2(255 char), type varchar2(255 char), base_entity number(19,0) not null, primary key (id), unique (name, base_entity));
create table reward (id number(19,0) not null, background_image_hash varchar2(255 char), body varchar2(255 char), email_confirm number(1,0), end_date date, fulfiled_date date, name varchar2(255 char) not null, notes varchar2(255 char), num_awarded number(10,0), quiz_enabled number(1,0) not null, quiz_html varchar2(255 char), start_date date, static_message varchar2(255 char), static_message_enabled number(1,0) not null, status varchar2(255 char), title varchar2(255 char) not null, user_text_enabled number(1,0) not null, user_text_message varchar2(255 char), user_upload_enabled number(1,0) not null, user_upload_message varchar2(255 char), organisation number(19,0) not null, primary key (id), unique (name, organisation));
create table reward_entry (id number(19,0) not null, awarded_date date not null, reason varchar2(255 char) not null, awarded_for number(19,0), awarded_to number(19,0) not null, reward number(19,0) not null, primary key (id));
create table signup_log (id number(19,0) not null, req_date timestamp not null, req_day number(10,0) not null, req_hour number(10,0) not null, req_month number(10,0) not null, req_year number(10,0) not null, group_entity number(19,0), membership_org number(19,0), organisation number(19,0), profile number(19,0), website number(19,0), primary key (id));
create table sub_org (id number(19,0) not null, owner number(19,0) not null, suborg number(19,0) not null, primary key (id));
create table subordinate (id number(19,0) not null, group_membership number(19,0) not null, within_org number(19,0) not null, primary key (id));
create table version (id number(19,0) not null, mod_date timestamp not null, mod_hash varchar2(255 char) not null, previous_mod_hash varchar2(255 char) not null, profile_id number(19,0) not null, resource_hash varchar2(255 char) not null, primary key (id));
create table website (domain_name varchar2(255 char), mail_server varchar2(255 char), redirect_to varchar2(255 char), id number(19,0) not null, alias_to number(19,0), organisation number(19,0) not null, primary key (id), unique (domain_name));
alter table access_log add constraint FKBBF335E9C4027D76 foreign key (organisation) references org_entity;
alter table access_log add constraint FKBBF335E91D457434 foreign key (website) references website;
alter table address_book add constraint FKFB8B0542CB36CA7 foreign key (id) references repository;
alter table app_control add constraint FKEE00D53FC4027D76 foreign key (organisation) references org_entity;
alter table app_control add constraint FKEE00D53F1CD5CA34 foreign key (modified_by) references profile;
alter table app_control add constraint FKEE00D53F849B88AA foreign key (website_branch) references branch;
alter table app_setting add constraint FK2BA87E323BD6907C foreign key (app_control) references app_control;
alter table base_email_job add constraint FK2F3D58ACC4027D76 foreign key (organisation) references org_entity;
create index ids_entity_name on base_entity (name);
create index ids_blobhash on blob_hash (blob_hash);
alter table branch add constraint FKADAF25A2EDBCEC59 foreign key (head) references commit_item;
alter table branch add constraint FKADAF25A2A0FA3AD6 foreign key (repository) references repository;
alter table branch add constraint FKADAF25A2DE9B19E5 foreign key (from_commit) references commit_item;
alter table cal_event add constraint FKABCCC2E9C9A2A33E foreign key (calendar) references calendar;
alter table cal_event_process add constraint FK68508F19CBDEA377 foreign key (id) references base_process;
alter table cal_event_process add constraint FK68508F197E512317 foreign key (cal_event) references cal_event;
alter table calendar add constraint FKF55EFB3E75CB2D09 foreign key (owner) references base_entity;
alter table certificate add constraint FK745F4197C4027D76 foreign key (organisation) references org_entity;
alter table comment add constraint FK38A5EE5F889319BC foreign key (id) references post;
alter table commit_item add constraint FK5A19351B2AEC5E14 foreign key (editor) references profile;
alter table commit_item add constraint FK5A19351B99AB4086 foreign key (branch) references branch;
alter table contact add constraint FK38B7242012BCE54F foreign key (address_book) references address_book;
alter table contact_extended_property add constraint FK8C45B7BCFCBFFB3E foreign key (contact) references contact;
alter table credential add constraint FKD743E857666EC650 foreign key (profile) references profile;
alter table email_item add constraint FK4E94C9D642E056DC foreign key (sender) references profile;
alter table email_item add constraint FK4E94C9D6A058AC6F foreign key (recipient) references base_entity;
alter table email_item add constraint FK4E94C9D67DB36992 foreign key (email_trigger) references email_trigger;
alter table email_item add constraint FK4E94C9D6AACF6B30 foreign key (job) references base_email_job;
alter table email_send_attempt add constraint FK7EF81CD9C331BB44 foreign key (email_item) references email_item;
alter table email_trigger add constraint FKD75DEC15AACDDC8E foreign key (id) references base_email_job;
alter table enrolement add constraint FK688BE7D1D457434 foreign key (website) references website;
alter table enrolement add constraint FK688BE7D73B79E62 foreign key (enroled_group) references group_entity;
create index ids_chunk_hash on fanout_entry (chunk_hash);
alter table fanout_entry add constraint FKD6C6228E4FF762A6 foreign key (fanout) references fanout_hash;
alter table forum add constraint FK5D18D211D457434 foreign key (website) references website;
alter table forum_post add constraint FKCDDDD0FE889319BC foreign key (id) references post;
alter table forum_post add constraint FKCDDDD0FE8F132661 foreign key (forum) references forum;
alter table forum_reply add constraint FKEDF3E64C889319BC foreign key (id) references post;
alter table forum_reply add constraint FKEDF3E64C70AD9EA0 foreign key (post) references forum_post;
alter table group_email_job add constraint FKF4C306DAAACDDC8E foreign key (id) references base_email_job;
alter table group_entity add constraint FKDC016DA3C4027D76 foreign key (organisation) references org_entity;
alter table group_in_website add constraint FK121949416A085208 foreign key (user_group) references group_entity;
alter table group_in_website add constraint FK121949411D457434 foreign key (website) references website;
alter table group_membership add constraint FK526319638A2C741 foreign key (member) references profile;
alter table group_membership add constraint FK5263196D360BEA0 foreign key (group_entity) references group_entity;
alter table group_membership add constraint FK526319630DCD1AC foreign key (within_org) references org_entity;
alter table group_membership_application add constraint FK88BAE42738A2C741 foreign key (member) references profile;
alter table group_membership_application add constraint FK88BAE427D360BEA0 foreign key (group_entity) references group_entity;
alter table group_membership_application add constraint FK88BAE42730DCD1AC foreign key (within_org) references org_entity;
alter table group_membership_application add constraint FK88BAE4271D457434 foreign key (website) references website;
alter table group_membership_application add constraint FK88BAE4278B021E90 foreign key (admin_org) references org_entity;
alter table group_recipient add constraint FKA73C90592840C316 foreign key (recipient) references group_entity;
alter table group_recipient add constraint FKA73C9059AACF6B30 foreign key (job) references base_email_job;
alter table group_reward add constraint FKF1B2D8EF1FA8C924 foreign key (reward) references reward;
alter table group_reward add constraint FKF1B2D8EF111E7CB0 foreign key (group_to_reward) references group_entity;
alter table group_role add constraint FK4C707A3630DCD1AC foreign key (within_org) references org_entity;
alter table group_role add constraint FK4C707A36A0FA3AD6 foreign key (repository) references repository;
alter table group_role add constraint FK4C707A3681447B9 foreign key (grantee) references group_entity;
alter table learner_process add constraint FKADA71E21CBDEA377 foreign key (id) references base_process;
alter table learner_process add constraint FKADA71E21666EC650 foreign key (profile) references profile;
alter table learning_log add constraint FKAA3686A3C4027D76 foreign key (organisation) references org_entity;
alter table learning_log add constraint FKAA3686A31D457434 foreign key (website) references website;
alter table learning_log add constraint FKAA3686A3666EC650 foreign key (profile) references profile;
alter table membership_process add constraint FKC4F81706CBDEA377 foreign key (id) references base_process;
alter table module_status add constraint FKA7AA55251D457434 foreign key (website) references website;
alter table module_status add constraint FKA7AA5525666EC650 foreign key (profile) references profile;
alter table module_status_field add constraint FK7F08296042C9B4E9 foreign key (module_status) references module_status;
alter table module_status_process add constraint FKFE862555CBDEA377 foreign key (id) references base_process;
alter table module_status_process add constraint FKFE86255542C9B4E9 foreign key (module_status) references module_status;
alter table nv_pair add constraint FK89B86AF1E979F767 foreign key (base_entity) references base_entity;
create index idx_orgId on org_entity (org_id);
alter table org_entity add constraint FK11F8699E6F774771 foreign key (id) references base_entity;
alter table org_entity add constraint FK11F8699EC4027D76 foreign key (organisation) references org_entity;
alter table password_reset add constraint FKF4CE9AAB1D457434 foreign key (website) references website;
alter table password_reset add constraint FKF4CE9AAB666EC650 foreign key (profile) references profile;
alter table post add constraint FK3498A01D457434 foreign key (website) references website;
alter table post add constraint FK3498A03E5139F4 foreign key (poster) references profile;
create index ids_profile_email on profile (email);
alter table profile add constraint FKED8E89A96F774771 foreign key (id) references base_entity;
alter table quiz_answer add constraint FKFD1EC0E8E07A0695 foreign key (quiz_attempt) references quiz_attempt;
alter table quiz_attempt add constraint FKB0FC76E342C9B4E9 foreign key (module_status) references module_status;
alter table repository add constraint FK7446DB4AE979F767 foreign key (base_entity) references base_entity;
alter table reward add constraint FKC84F4F2FC4027D76 foreign key (organisation) references org_entity;
alter table reward_entry add constraint FK7B7C5B621FA8C924 foreign key (reward) references reward;
alter table reward_entry add constraint FK7B7C5B628FBEE285 foreign key (awarded_to) references profile;
alter table reward_entry add constraint FK7B7C5B626015418A foreign key (awarded_for) references module_status;
alter table signup_log add constraint FKE193F79DD360BEA0 foreign key (group_entity) references group_entity;
alter table signup_log add constraint FKE193F79DC4027D76 foreign key (organisation) references org_entity;
alter table signup_log add constraint FKE193F79D1D457434 foreign key (website) references website;
alter table signup_log add constraint FKE193F79D666EC650 foreign key (profile) references profile;
alter table signup_log add constraint FKE193F79D5DA60797 foreign key (membership_org) references org_entity;
alter table sub_org add constraint FK90A57C65548BC540 foreign key (suborg) references org_entity;
alter table sub_org add constraint FK90A57C6590036F4F foreign key (owner) references org_entity;
alter table subordinate add constraint FK9448134C30DCD1AC foreign key (within_org) references org_entity;
alter table subordinate add constraint FK9448134C56958E49 foreign key (group_membership) references group_membership;
create index idx_version_modhash on version (mod_hash);
create index idx_domain_name on website (domain_name);
alter table website add constraint FK48F9E09B2CB36CA7 foreign key (id) references repository;
alter table website add constraint FK48F9E09BC4027D76 foreign key (organisation) references org_entity;
alter table website add constraint FK48F9E09B3A780E63 foreign key (alias_to) references website;
create sequence hibernate_sequence;
