drop table address_book cascade constraints;
drop table alt_format cascade constraints;
drop table app_control cascade constraints;
drop table base_entity cascade constraints;
drop table blob_hash cascade constraints;
drop table branch cascade constraints;
drop table cal_event cascade constraints;
drop table calendar cascade constraints;
drop table comment cascade constraints;
drop table commit_item cascade constraints;
drop table contact cascade constraints;
drop table contact_extended_properties cascade constraints;
drop table contact_extended_property cascade constraints;
drop table credential cascade constraints;
drop table data_item cascade constraints;
drop table email_item cascade constraints;
drop table email_send_attempt cascade constraints;
drop table fanout_entry cascade constraints;
drop table fanout_hash cascade constraints;
drop table forum cascade constraints;
drop table forum_post cascade constraints;
drop table forum_reply cascade constraints;
drop table forum_topic cascade constraints;
drop table group_email_job cascade constraints;
drop table group_entity cascade constraints;
drop table group_membership cascade constraints;
drop table group_recipient cascade constraints;
drop table item_history cascade constraints;
drop table named_counter cascade constraints;
drop table nv_pair cascade constraints;
drop table org_entity cascade constraints;
drop table permission cascade constraints;
drop table post cascade constraints;
drop table profile cascade constraints;
drop table repository cascade constraints;
drop table version cascade constraints;
drop table website cascade constraints;
drop sequence hibernate_sequence;
create table address_book (id number(19,0) not null, description varchar2(255 char), created_date timestamp not null, modified_date timestamp not null, name varchar2(255 char) not null, owner number(19,0), primary key (id));
create table alt_format (id number(19,0) not null, source_hash number(19,0) not null, alt_hash number(19,0) not null, name varchar2(255 char) not null, primary key (id), unique (name, source_hash));
create table app_control (id number(19,0) not null, modified_date timestamp not null, enabled number(1,0) not null, name varchar2(255 char) not null, organisation number(19,0), modified_by number(19,0) not null, website number(19,0), primary key (id));
create table base_entity (id number(19,0) not null, created_date timestamp not null, modified_date timestamp not null, notes varchar2(255 char), name varchar2(255 char) not null, type varchar2(255 char), organisation number(19,0), primary key (id), unique (name, organisation));
create table blob_hash (blob_hash number(19,0) not null, volume_id number(19,0) not null, primary key (blob_hash));
create table branch (id number(19,0) not null, created_date timestamp, lockversion number(19,0), name varchar2(255 char), head number(19,0) not null, repository number(19,0) not null, primary key (id));
create table cal_event (id number(19,0) not null, description varchar2(255 char), created_date timestamp not null, modified_date timestamp not null, ctag number(19,0) not null, start_date timestamp not null, end_date timestamp not null, timezone varchar2(255 char), summary varchar2(255 char), name varchar2(255 char) not null, calendar number(19,0) not null, primary key (id));
create table calendar (id number(19,0) not null, created_date timestamp not null, modified_date timestamp not null, color varchar2(255 char), ctag number(19,0) not null, name varchar2(255 char) not null, owner number(19,0) not null, primary key (id), unique (name, owner));
create table comment (id number(19,0) not null, content_id raw(255) not null, content_href varchar2(255 char) not null, content_title varchar2(255 char) not null, primary key (id));
create table commit_item (id number(19,0) not null, created_date timestamp, item_hash number(19,0), editor number(19,0) not null, primary key (id));
create table contact (id number(19,0) not null, created_date timestamp not null, modified_date timestamp not null, sur_name varchar2(255 char), given_name varchar2(255 char), mail varchar2(255 char), organization_name varchar2(255 char), telephonenumber varchar2(255 char), uid varchar2(255 char) not null, name varchar2(255 char) not null, address_book number(19,0) not null, primary key (id));
create table contact_extended_properties (contact number(19,0) not null, extended_properties number(19,0) not null, unique (extended_properties));
create table contact_extended_property (id number(19,0) not null, prop_value varchar2(255 char) not null, name varchar2(255 char) not null, contact number(19,0) not null, primary key (id));
create table credential (type varchar2(20 char) not null, id number(19,0) not null, created_date timestamp not null, modified_date timestamp not null, password varchar2(255 char) not null, profile number(19,0) not null, primary key (id));
create table data_item (id number(19,0) not null, item_hash number(19,0) not null, parent_hash number(19,0) not null, name varchar2(1000 char), type varchar2(1 char) not null, primary key (id), unique (name, parent_hash));
create table email_item (id number(19,0) not null, created_date timestamp not null, reply_to_address varchar2(255 char) not null, subject varchar2(255 char) not null, html varchar2(255 char), send_status varchar2(255 char), send_status_date timestamp not null, read_status number(1,0) not null, message_size number(10,0) not null, disposition varchar2(255 char), bcc_list varchar2(255 char), cc_list varchar2(255 char), content_language varchar2(255 char), to_list varchar2(255 char), from_address varchar2(255 char) not null, recipient_address varchar2(255 char) not null, text varchar2(255 char), encoding varchar2(255 char), sender number(19,0), job number(19,0), recipient number(19,0), primary key (id));
create table email_send_attempt (id number(19,0) not null, status_date timestamp not null, status varchar2(255 char), email_item number(19,0) not null, primary key (id));
create table fanout_entry (id number(19,0) not null, chunk_hash number(19,0), fanout number(19,0), primary key (id));
create table fanout_hash (fanout_hash number(19,0) not null, actual_content_length number(19,0) not null, primary key (fanout_hash));
create table forum (id number(19,0) not null, notes varchar2(255 char), title varchar2(255 char) not null, name varchar2(255 char) not null, website number(19,0) not null, primary key (id));
create table forum_post (id number(19,0) not null, title varchar2(255 char) not null, name varchar2(255 char) not null, topic number(19,0) not null, primary key (id));
create table forum_reply (id number(19,0) not null, post number(19,0) not null, primary key (id));
create table forum_topic (id number(19,0) not null, notes varchar2(255 char), title varchar2(255 char) not null, name varchar2(255 char) not null, forum number(19,0) not null, primary key (id));
create table group_email_job (id number(19,0) not null, notes varchar2(255 char), title varchar2(255 char) not null, subject varchar2(255 char) not null, from_address varchar2(255 char) not null, status_date timestamp not null, status varchar2(255 char), name varchar2(255 char) not null, organisation number(19,0) not null, primary key (id));
create table group_entity (id number(19,0) not null, primary key (id));
create table group_membership (id number(19,0) not null, created_date timestamp not null, modified_date timestamp not null, group_entity number(19,0) not null, member number(19,0) not null, primary key (id));
create table group_recipient (id number(19,0) not null, job number(19,0) not null, recipient number(19,0) not null, primary key (id));
create table item_history (id number(19,0) not null, tree_item raw(255) not null, parent_tree_item raw(255) not null, action varchar2(255 char) not null, name varchar2(1000 char), primary key (id));
create table named_counter (id number(19,0) not null, counter number(19,0) not null, name varchar2(255 char), primary key (id));
create table nv_pair (id number(19,0) not null, prop_value varchar2(255 char) not null, name varchar2(255 char) not null, repository number(19,0), base_entity number(19,0), primary key (id));
create table org_entity (id number(19,0) not null, primary key (id));
create table permission (id number(19,0) not null, grantee_principal varchar2(255 char), priviledge number(10,0), granted_on_entity number(19,0), grantee number(19,0), granted_on_branch number(19,0), primary key (id));
create table post (id number(19,0) not null, notes varchar2(255 char), post_date timestamp not null, website number(19,0) not null, poster number(19,0) not null, primary key (id));
create table profile (id number(19,0) not null, email varchar2(255 char), sur_name varchar2(255 char), first_name varchar2(255 char), nick_name varchar2(255 char), photo_href varchar2(255 char), phone varchar2(255 char), admin_org number(19,0) not null, primary key (id));
create table repository (id number(19,0) not null, created_date timestamp not null, notes varchar2(255 char), title varchar2(255 char), name varchar2(255 char) not null, base_entity number(19,0) not null, primary key (id), unique (name, base_entity));
create table version (id number(19,0) not null, resource_hash number(19,0) not null, previous_mod_hash number(19,0) not null, profile_id number(19,0) not null, mod_date timestamp not null, mod_hash number(19,0) not null, primary key (id));
create table website (id number(19,0) not null, created_date timestamp not null, internal_theme varchar2(255 char), public_theme varchar2(255 char), current_branch varchar2(255 char), name varchar2(255 char) not null, repository number(19,0) not null, organisation number(19,0) not null, primary key (id));
alter table address_book add constraint FKFB8B05475CB2D09 foreign key (owner) references base_entity;
alter table app_control add constraint FKEE00D53FC4027D76 foreign key (organisation) references org_entity;
alter table app_control add constraint FKEE00D53F1D457434 foreign key (website) references website;
alter table app_control add constraint FKEE00D53F1CD5CA34 foreign key (modified_by) references profile;
alter table base_entity add constraint FK7A02BD11C4027D76 foreign key (organisation) references org_entity;
alter table branch add constraint FKADAF25A2EDBCEC59 foreign key (head) references commit_item;
alter table branch add constraint FKADAF25A2A0FA3AD6 foreign key (repository) references repository;
alter table cal_event add constraint FKABCCC2E9C9A2A33E foreign key (calendar) references calendar;
alter table calendar add constraint FKF55EFB3E75CB2D09 foreign key (owner) references base_entity;
alter table comment add constraint FK38A5EE5F889319BC foreign key (id) references post;
alter table commit_item add constraint FK5A19351B2AEC5E14 foreign key (editor) references profile;
alter table contact add constraint FK38B7242012BCE54F foreign key (address_book) references address_book;
alter table contact_extended_properties add constraint FK91B6895A8A92AD65 foreign key (extended_properties) references contact_extended_property;
alter table contact_extended_properties add constraint FK91B6895AFCBFFB3E foreign key (contact) references contact;
alter table contact_extended_property add constraint FK8C45B7BCFCBFFB3E foreign key (contact) references contact;
alter table credential add constraint FKD743E857666EC650 foreign key (profile) references profile;
alter table email_item add constraint FK4E94C9D642E056DC foreign key (sender) references profile;
alter table email_item add constraint FK4E94C9D6A9C1AEC0 foreign key (recipient) references profile;
alter table email_item add constraint FK4E94C9D6E4A566FC foreign key (job) references group_email_job;
alter table email_send_attempt add constraint FK7EF81CD9C331BB44 foreign key (email_item) references email_item;
alter table fanout_entry add constraint FKD6C6228E4FF762A6 foreign key (fanout) references fanout_hash;
alter table forum add constraint FK5D18D211D457434 foreign key (website) references website;
alter table forum_post add constraint FKCDDDD0FE889319BC foreign key (id) references post;
alter table forum_post add constraint FKCDDDD0FEA576D8FE foreign key (topic) references forum_topic;
alter table forum_reply add constraint FKEDF3E64C889319BC foreign key (id) references post;
alter table forum_reply add constraint FKEDF3E64C70AD9EA0 foreign key (post) references forum_post;
alter table forum_topic add constraint FKEE14A0918F132661 foreign key (forum) references forum;
alter table group_email_job add constraint FKF4C306DAC4027D76 foreign key (organisation) references org_entity;
alter table group_entity add constraint FKDC016DA36F774771 foreign key (id) references base_entity;
alter table group_membership add constraint FK52631962F39C4F0 foreign key (member) references base_entity;
alter table group_membership add constraint FK5263196D360BEA0 foreign key (group_entity) references group_entity;
alter table group_recipient add constraint FKA73C90592840C316 foreign key (recipient) references group_entity;
alter table group_recipient add constraint FKA73C9059E4A566FC foreign key (job) references group_email_job;
alter table nv_pair add constraint FK89B86AF1E979F767 foreign key (base_entity) references base_entity;
alter table nv_pair add constraint FK89B86AF1A0FA3AD6 foreign key (repository) references repository;
alter table org_entity add constraint FK11F8699E6F774771 foreign key (id) references base_entity;
alter table permission add constraint FKE125C5CF1551AA62 foreign key (granted_on_branch) references branch;
alter table permission add constraint FKE125C5CF802C3112 foreign key (grantee) references base_entity;
alter table permission add constraint FKE125C5CF9DBB8815 foreign key (granted_on_entity) references base_entity;
alter table post add constraint FK3498A01D457434 foreign key (website) references website;
alter table post add constraint FK3498A03E5139F4 foreign key (poster) references profile;
alter table profile add constraint FKED8E89A96F774771 foreign key (id) references base_entity;
alter table profile add constraint FKED8E89A98B021E90 foreign key (admin_org) references org_entity;
alter table repository add constraint FK7446DB4AE979F767 foreign key (base_entity) references base_entity;
alter table website add constraint FK48F9E09BC4027D76 foreign key (organisation) references org_entity;
alter table website add constraint FK48F9E09BA0FA3AD6 foreign key (repository) references repository;
create sequence hibernate_sequence;
