alter table address_book drop constraint FKFB8B05475CB2D09;
alter table app_control drop constraint FKEE00D53FC4027D76;
alter table app_control drop constraint FKEE00D53F1D457434;
alter table app_control drop constraint FKEE00D53F1CD5CA34;
alter table base_entity drop constraint FK7A02BD11C4027D76;
alter table branch drop constraint FKADAF25A2EDBCEC59;
alter table branch drop constraint FKADAF25A2A0FA3AD6;
alter table cal_event drop constraint FKABCCC2E9C9A2A33E;
alter table calendar drop constraint FKF55EFB3E75CB2D09;
alter table comment drop constraint FK38A5EE5F889319BC;
alter table commit_item drop constraint FK5A19351B2AEC5E14;
alter table contact drop constraint FK38B7242012BCE54F;
alter table contact_extended_properties drop constraint FK91B6895A8A92AD65;
alter table contact_extended_properties drop constraint FK91B6895AFCBFFB3E;
alter table contact_extended_property drop constraint FK8C45B7BCFCBFFB3E;
alter table credential drop constraint FKD743E857666EC650;
alter table email_item drop constraint FK4E94C9D642E056DC;
alter table email_item drop constraint FK4E94C9D6A9C1AEC0;
alter table email_item drop constraint FK4E94C9D6E4A566FC;
alter table email_send_attempt drop constraint FK7EF81CD9C331BB44;
alter table fanout_entry drop constraint FKD6C6228E4FF762A6;
alter table forum drop constraint FK5D18D211D457434;
alter table forum_post drop constraint FKCDDDD0FE889319BC;
alter table forum_post drop constraint FKCDDDD0FEA576D8FE;
alter table forum_reply drop constraint FKEDF3E64C889319BC;
alter table forum_reply drop constraint FKEDF3E64C70AD9EA0;
alter table forum_topic drop constraint FKEE14A0918F132661;
alter table group_email_job drop constraint FKF4C306DAC4027D76;
alter table group_entity drop constraint FKDC016DA36F774771;
alter table group_membership drop constraint FK52631962F39C4F0;
alter table group_membership drop constraint FK5263196D360BEA0;
alter table group_recipient drop constraint FKA73C90592840C316;
alter table group_recipient drop constraint FKA73C9059E4A566FC;
alter table nv_pair drop constraint FK89B86AF1E979F767;
alter table nv_pair drop constraint FK89B86AF1A0FA3AD6;
alter table org_entity drop constraint FK11F8699E6F774771;
alter table permission drop constraint FKE125C5CF1551AA62;
alter table permission drop constraint FKE125C5CF802C3112;
alter table permission drop constraint FKE125C5CF9DBB8815;
alter table post drop constraint FK3498A01D457434;
alter table post drop constraint FK3498A03E5139F4;
alter table profile drop constraint FKED8E89A96F774771;
alter table profile drop constraint FKED8E89A98B021E90;
alter table repository drop constraint FK7446DB4AE979F767;
alter table website drop constraint FK48F9E09BC4027D76;
alter table website drop constraint FK48F9E09BA0FA3AD6;
drop table address_book;
drop table alt_format;
drop table app_control;
drop table base_entity;
drop table blob_hash;
drop table branch;
drop table cal_event;
drop table calendar;
drop table comment;
drop table commit_item;
drop table contact;
drop table contact_extended_properties;
drop table contact_extended_property;
drop table credential;
drop table data_item;
drop table email_item;
drop table email_send_attempt;
drop table fanout_entry;
drop table fanout_hash;
drop table forum;
drop table forum_post;
drop table forum_reply;
drop table forum_topic;
drop table group_email_job;
drop table group_entity;
drop table group_membership;
drop table group_recipient;
drop table item_history;
drop table named_counter;
drop table nv_pair;
drop table org_entity;
drop table permission;
drop table post;
drop table profile;
drop table repository;
drop table version;
drop table website;
drop sequence hibernate_sequence;
create table address_book (id int8 not null, description varchar(255), created_date timestamp not null, modified_date timestamp not null, name varchar(255) not null, owner int8, primary key (id));
create table alt_format (id int8 not null, source_hash int8 not null, alt_hash int8 not null, name varchar(255) not null, primary key (id), unique (name, source_hash));
create table app_control (id int8 not null, modified_date timestamp not null, enabled bool not null, name varchar(255) not null, organisation int8, modified_by int8 not null, website int8, primary key (id));
create table base_entity (id int8 not null, created_date timestamp not null, modified_date timestamp not null, notes varchar(255), name varchar(255) not null, type varchar(255), organisation int8, primary key (id), unique (name, organisation));
create table blob_hash (blob_hash int8 not null, volume_id int8 not null, primary key (blob_hash));
create table branch (id int8 not null, created_date timestamp, lockversion int8, name varchar(255), head int8 not null, repository int8 not null, primary key (id));
create table cal_event (id int8 not null, description varchar(255), created_date timestamp not null, modified_date timestamp not null, ctag int8 not null, start_date timestamp not null, end_date timestamp not null, timezone varchar(255), summary varchar(255), name varchar(255) not null, calendar int8 not null, primary key (id));
create table calendar (id int8 not null, created_date timestamp not null, modified_date timestamp not null, color varchar(255), ctag int8 not null, name varchar(255) not null, owner int8 not null, primary key (id), unique (name, owner));
create table comment (id int8 not null, content_id bytea not null, content_href varchar(255) not null, content_title varchar(255) not null, primary key (id));
create table commit_item (id int8 not null, created_date timestamp, item_hash int8, editor int8 not null, primary key (id));
create table contact (id int8 not null, created_date timestamp not null, modified_date timestamp not null, sur_name varchar(255), given_name varchar(255), mail varchar(255), organization_name varchar(255), telephonenumber varchar(255), uid varchar(255) not null, name varchar(255) not null, address_book int8 not null, primary key (id));
create table contact_extended_properties (contact int8 not null, extended_properties int8 not null, unique (extended_properties));
create table contact_extended_property (id int8 not null, prop_value varchar(255) not null, name varchar(255) not null, contact int8 not null, primary key (id));
create table credential (type varchar(20) not null, id int8 not null, created_date timestamp not null, modified_date timestamp not null, password varchar(255) not null, profile int8 not null, primary key (id));
create table data_item (id int8 not null, item_hash int8 not null, parent_hash int8 not null, name varchar(1000), type varchar(1) not null, primary key (id), unique (name, parent_hash));
create table email_item (id int8 not null, created_date timestamp not null, reply_to_address varchar(255) not null, subject varchar(255) not null, html varchar(255), send_status varchar(255), send_status_date timestamp not null, read_status bool not null, message_size int4 not null, disposition varchar(255), bcc_list varchar(255), cc_list varchar(255), content_language varchar(255), to_list varchar(255), from_address varchar(255) not null, recipient_address varchar(255) not null, text varchar(255), encoding varchar(255), sender int8, job int8, recipient int8, primary key (id));
create table email_send_attempt (id int8 not null, status_date timestamp not null, status varchar(255), email_item int8 not null, primary key (id));
create table fanout_entry (id int8 not null, chunk_hash int8, fanout int8, primary key (id));
create table fanout_hash (fanout_hash int8 not null, actual_content_length int8 not null, primary key (fanout_hash));
create table forum (id int8 not null, notes varchar(255), title varchar(255) not null, name varchar(255) not null, website int8 not null, primary key (id));
create table forum_post (id int8 not null, title varchar(255) not null, name varchar(255) not null, topic int8 not null, primary key (id));
create table forum_reply (id int8 not null, post int8 not null, primary key (id));
create table forum_topic (id int8 not null, notes varchar(255), title varchar(255) not null, name varchar(255) not null, forum int8 not null, primary key (id));
create table group_email_job (id int8 not null, notes varchar(255), title varchar(255) not null, subject varchar(255) not null, from_address varchar(255) not null, status_date timestamp not null, status varchar(255), name varchar(255) not null, organisation int8 not null, primary key (id));
create table group_entity (id int8 not null, primary key (id));
create table group_membership (id int8 not null, created_date timestamp not null, modified_date timestamp not null, group_entity int8 not null, member int8 not null, primary key (id));
create table group_recipient (id int8 not null, job int8 not null, recipient int8 not null, primary key (id));
create table item_history (id int8 not null, tree_item bytea not null, parent_tree_item bytea not null, action varchar(255) not null, name varchar(1000), primary key (id));
create table named_counter (id int8 not null, counter int8 not null, name varchar(255), primary key (id));
create table nv_pair (id int8 not null, prop_value varchar(255) not null, name varchar(255) not null, repository int8, base_entity int8, primary key (id));
create table org_entity (id int8 not null, primary key (id));
create table permission (id int8 not null, grantee_principal varchar(255), priviledge int4, granted_on_entity int8, grantee int8, granted_on_branch int8, primary key (id));
create table post (id int8 not null, notes varchar(255), post_date timestamp not null, website int8 not null, poster int8 not null, primary key (id));
create table profile (id int8 not null, email varchar(255), sur_name varchar(255), first_name varchar(255), nick_name varchar(255), photo_href varchar(255), phone varchar(255), admin_org int8 not null, primary key (id));
create table repository (id int8 not null, created_date timestamp not null, notes varchar(255), title varchar(255), name varchar(255) not null, base_entity int8 not null, primary key (id), unique (name, base_entity));
create table version (id int8 not null, resource_hash int8 not null, previous_mod_hash int8 not null, profile_id int8 not null, mod_date timestamp not null, mod_hash int8 not null, primary key (id));
create table website (id int8 not null, created_date timestamp not null, internal_theme varchar(255), public_theme varchar(255), current_branch varchar(255), name varchar(255) not null, repository int8 not null, organisation int8 not null, primary key (id));
alter table address_book add constraint FKFB8B05475CB2D09 foreign key (owner) references base_entity;
alter table app_control add constraint FKEE00D53FC4027D76 foreign key (organisation) references org_entity;
alter table app_control add constraint FKEE00D53F1D457434 foreign key (website) references website;
alter table app_control add constraint FKEE00D53F1CD5CA34 foreign key (modified_by) references profile;
alter table base_entity add constraint FK7A02BD11C4027D76 foreign key (organisation) references org_entity;
alter table branch add constraint FKADAF25A2EDBCEC59 foreign key (head) references commit_item;
alter table branch add constraint FKADAF25A2A0FA3AD6 foreign key (repository) references repository;
alter table cal_event add constraint FKABCCC2E9C9A2A33E foreign key (calendar) references calendar;
alter table calendar add constraint FKF55EFB3E75CB2D09 foreign key (owner) references base_entity;
alter table comment add constraint FK38A5EE5F889319BC foreign key (id) references post;
alter table commit_item add constraint FK5A19351B2AEC5E14 foreign key (editor) references profile;
alter table contact add constraint FK38B7242012BCE54F foreign key (address_book) references address_book;
alter table contact_extended_properties add constraint FK91B6895A8A92AD65 foreign key (extended_properties) references contact_extended_property;
alter table contact_extended_properties add constraint FK91B6895AFCBFFB3E foreign key (contact) references contact;
alter table contact_extended_property add constraint FK8C45B7BCFCBFFB3E foreign key (contact) references contact;
alter table credential add constraint FKD743E857666EC650 foreign key (profile) references profile;
alter table email_item add constraint FK4E94C9D642E056DC foreign key (sender) references profile;
alter table email_item add constraint FK4E94C9D6A9C1AEC0 foreign key (recipient) references profile;
alter table email_item add constraint FK4E94C9D6E4A566FC foreign key (job) references group_email_job;
alter table email_send_attempt add constraint FK7EF81CD9C331BB44 foreign key (email_item) references email_item;
alter table fanout_entry add constraint FKD6C6228E4FF762A6 foreign key (fanout) references fanout_hash;
alter table forum add constraint FK5D18D211D457434 foreign key (website) references website;
alter table forum_post add constraint FKCDDDD0FE889319BC foreign key (id) references post;
alter table forum_post add constraint FKCDDDD0FEA576D8FE foreign key (topic) references forum_topic;
alter table forum_reply add constraint FKEDF3E64C889319BC foreign key (id) references post;
alter table forum_reply add constraint FKEDF3E64C70AD9EA0 foreign key (post) references forum_post;
alter table forum_topic add constraint FKEE14A0918F132661 foreign key (forum) references forum;
alter table group_email_job add constraint FKF4C306DAC4027D76 foreign key (organisation) references org_entity;
alter table group_entity add constraint FKDC016DA36F774771 foreign key (id) references base_entity;
alter table group_membership add constraint FK52631962F39C4F0 foreign key (member) references base_entity;
alter table group_membership add constraint FK5263196D360BEA0 foreign key (group_entity) references group_entity;
alter table group_recipient add constraint FKA73C90592840C316 foreign key (recipient) references group_entity;
alter table group_recipient add constraint FKA73C9059E4A566FC foreign key (job) references group_email_job;
alter table nv_pair add constraint FK89B86AF1E979F767 foreign key (base_entity) references base_entity;
alter table nv_pair add constraint FK89B86AF1A0FA3AD6 foreign key (repository) references repository;
alter table org_entity add constraint FK11F8699E6F774771 foreign key (id) references base_entity;
alter table permission add constraint FKE125C5CF1551AA62 foreign key (granted_on_branch) references branch;
alter table permission add constraint FKE125C5CF802C3112 foreign key (grantee) references base_entity;
alter table permission add constraint FKE125C5CF9DBB8815 foreign key (granted_on_entity) references base_entity;
alter table post add constraint FK3498A01D457434 foreign key (website) references website;
alter table post add constraint FK3498A03E5139F4 foreign key (poster) references profile;
alter table profile add constraint FKED8E89A96F774771 foreign key (id) references base_entity;
alter table profile add constraint FKED8E89A98B021E90 foreign key (admin_org) references org_entity;
alter table repository add constraint FK7446DB4AE979F767 foreign key (base_entity) references base_entity;
alter table website add constraint FK48F9E09BC4027D76 foreign key (organisation) references org_entity;
alter table website add constraint FK48F9E09BA0FA3AD6 foreign key (repository) references repository;
create sequence hibernate_sequence;
